<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy" data-toc-modified-id="NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy</a></span><ul class="toc-item"><li><span><a href="#Homework" data-toc-modified-id="Homework-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Homework</a></span></li></ul></li></ul></div>

# NumPy

NumPy è una libreria open source per il linguaggio di programmazione Python, che aggiunge supporto a grandi **matrici**
e **array multidimensionali** insieme a una vasta collezione di funzioni matematiche di alto livello per poter operare 
efficientemente su queste strutture dati.

##### Le basi: come creo un array?

**Ricorda** : NumPy considera come array sia le matrici che i vettori! 

*Array* : insieme organizzato di elementi omogenei, identificati da uno stesso nome e da uno o più indici.

In [3]:
#importo la libreria di riferimento

import numpy as np

In [4]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
squares = np.array([x**2 for x in range(10)])
squares

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
type(squares)

numpy.ndarray

###### Metodi utili per array

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.dtype.name

'int32'

In [10]:
a.itemsize

4

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

###### Creare array a partire da tipi diversi in Python

La funzione **range( )** ritorna una sequenza di numeri, partendo da 0 di default, e incrementa di 1 (di default), e si ferma prima di uno specifico numero.

In [13]:
squares = [x**2 for x in range(10)]         # list
cubes = tuple(x**3 for x in range(10))      # tuple
evens = {x for x in range(10) if x%2 == 0}  # set

print(type(squares))
print(type(cubes))
print(type(evens))

<class 'list'>
<class 'tuple'>
<class 'set'>


In [14]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [15]:
cubes

(0, 1, 8, 27, 64, 125, 216, 343, 512, 729)

In [16]:
evens

{0, 2, 4, 6, 8}

In [17]:
a = np.array(squares)
b = np.array(cubes)
c = np.array(evens)

if type(a) == type(b) == type(c):
    print(type(a))

<class 'numpy.ndarray'>


In [18]:
seq2 = [[x, x**2, x**3] for x in range(10)]
seq3 = [[[x for x in range(3)], [y for y in range(3, 6)]] for z in range(10)]

a = np.array(seq2) 
b = np.array(seq3)

print(a.ndim)
print(b.ndim)

2
3


In [19]:
zeros = np.zeros((3, 3), dtype=np.int32) 
ones = np.ones((2, 2), dtype=np.float64)
empty = np.empty((3, 3))

print(zeros, zeros.dtype.name)
print(ones, ones.dtype.name)
print(empty, empty.dtype.name)

[[0 0 0]
 [0 0 0]
 [0 0 0]] int32
[[1. 1.]
 [1. 1.]] float64
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.05525742e-321]
 [1.11261570e-306 8.90060779e-307 3.49699467e-317]] float64


In [20]:
a = np.arange(5, 30, 5) 
a

array([ 5, 10, 15, 20, 25])

In [21]:
from numpy import pi

c = np.linspace(0, 2*pi, 10)

f = np.sin(c)
f

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [22]:
def f(row_num, col_num):
    return 2*row_num + col_num

F = np.fromfunction(f, (3, 3), dtype=int)
F

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

###### Stampare array

In [23]:
dim1 = np.arange(15)                  
dim2 = np.arange(15).reshape(3, 5)    
dim3 = np.arange(24).reshape(2, 3, 4)  
print(dim1)
print('\n')
print(dim2)
print('\n')
print(dim3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


###### Operazioni comuni con NumPy

In [24]:
a = np.arange(10) 
b = np.array([2 for x in range(10)])
c = np.ones(10, dtype=int)
result = a + b - c 

print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
result < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [26]:
a = np.ones(15).reshape(3, 5)
b = np.ones(15).reshape(5, 3)

mult = a * 10           
dot_prod1 = a.dot(b)   
dot_prod2 = np.dot(a, b)

print(mult, end='\n\n')
print(dot_prod1, end='\n\n')
print(dot_prod2)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [27]:
a = np.ones(10, dtype=int)
b = np.ones(10, dtype=float)
c = np.ones(10, dtype=complex)

a_plus_b = a + b 
b_plus_c = b + c 

print(a_plus_b.dtype.name)
print(b_plus_c.dtype.name)


float64
complex128


In [28]:
a = np.arange(1, 11)
print('Sum:', a.sum())
print('Min:', a.min())
print('Max:', a.max())

Sum: 55
Min: 1
Max: 10


In [29]:
a = np.arange(15).reshape(3, 5) + 1

print(a.sum(axis=0)) 
print(a.min(axis=1)) 
a

[18 21 24 27 30]
[ 1  6 11]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

###### Funzioni di diversa utilità

In [30]:
a = np.linspace(0, 2*pi, 10000)

sin_a = np.sin(a)
sqrt_a = np.sqrt(a)
exp_a = np.exp(a)

print(sin_a, end='\n\n')
print(sqrt_a, end='\n\n')
print(exp_a, end='\n\n')

[ 0.00000000e+00  6.28381328e-04  1.25676241e-03 ... -1.25676241e-03
 -6.28381328e-04 -2.44929360e-16]

[0.         0.02506754 0.03545085 ... 2.50637757 2.50650293 2.50662827]

[  1.           1.00062858   1.00125755 ... 534.81909228 535.15526825
 535.49165552]



##### Generazione numeri casuali

Per la generazione di array di numeri causali a partire da vari tipi di distribuzione statistica si utilizza il modulo *random*:

riferimento: https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html.

In [31]:
import numpy.random as rdm

In [32]:
A = rdm.random((4,4))
A

array([[0.34426277, 0.73148509, 0.2442391 , 0.22255624],
       [0.02394136, 0.29523404, 0.1119548 , 0.97853459],
       [0.54959539, 0.28515483, 0.83854653, 0.37956188],
       [0.10761892, 0.79692159, 0.88398509, 0.78268457]])

In [33]:
I = rdm.randint(1,7,(4,4))
I

array([[5, 5, 5, 6],
       [5, 6, 4, 1],
       [2, 3, 5, 4],
       [3, 1, 3, 5]])

In [34]:
N = rdm.normal(2,1,(4,6))
N

array([[ 2.11690628,  2.6065636 ,  2.63599063,  2.72183549,  1.45833065,
         1.62799328],
       [ 1.68205787, -0.1993807 ,  3.39602855,  2.06360943,  2.40906852,
         2.06659285],
       [-0.25328607,  3.34240778,  3.83830432,  2.71271934,  0.4890095 ,
         0.15108975],
       [-0.77260207,  1.51662161,  2.51691058,  2.21527332,  2.12841755,
         0.93735963]])

###### Indexing, slicing, and iterating

In [35]:
A = np.array([x**2 for x in range(1, 11)]).reshape(2, 5)

print(A, end='\n\n')
print('A[0]\t\t', A[0])
print('A[-1]\t\t', A[-1])
print('A[0][0]\t\t', A[0][0])
print('A[-1][-1]\t', A[-1][-1])


[[  1   4   9  16  25]
 [ 36  49  64  81 100]]

A[0]		 [ 1  4  9 16 25]
A[-1]		 [ 36  49  64  81 100]
A[0][0]		 1
A[-1][-1]	 100


In [36]:
cubes = np.arange(1, 13).reshape(4, 3)**3

print(cubes[:,:], end='\n\n')         
print('First Column:\t', cubes[:, 0]) 
print('Last Column:\t', cubes[:, -1]) 
print('First Row:\t', cubes[0, :])    
print('Last Row:\t', cubes[-1, :])

[[   1    8   27]
 [  64  125  216]
 [ 343  512  729]
 [1000 1331 1728]]

First Column:	 [   1   64  343 1000]
Last Column:	 [  27  216  729 1728]
First Row:	 [ 1  8 27]
Last Row:	 [1000 1331 1728]


In [37]:
A = np.array([x+1 for x in range(10)])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
for a in A:
    print(a, end=',')

1,2,3,4,5,6,7,8,9,10,

In [39]:
A = A.reshape(2, 5)

for a in A[0,:]: 
    print(a**2, end=',')

1,4,9,16,25,

###### Come splittare gli arrays

In [40]:
a = np.ones(9).reshape(3, 3)

a_1, a_2, a_3 = np.hsplit(a, 3)

print(a, end='\n\n')
print(a_1, end='\n\n')
print(a_2, end='\n\n')
print(a_3, end='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]



## Homework

- Crea una matrice 3x3 con valori compresi tra 0 e 8
- Crea un vettore random con 30 elementi e trova il valore medio
- Trova gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]
- Scrivi un programma per ottenere gli indici degli elementi ordinati di un dato array
    ,esempio : 
     - array: [1023 5202 6230 1671 1682 5241 4532]
     - indice degli elementi ordinati dell'array :[0 3 4 6 1 5 2]
- Scrivi un programma che calcola la media attraverso la dimensione, in un array 2D
    ,esempio : 
     - array:   
       [[10 30]
       
       [20 60]]
     - media di ogni colonna: [15 45]
     - media di ogni riga: [20 40]

Inoltre se volete continuare ad esercitarvi trovate una vasta gamma di esercizi di ogni tipologia su questo sito:
https://www.w3resource.com/python-exercises/numpy/index.php
    

In [10]:
import numpy as np
import numpy.random as rdm


#Matrice 3x3 con numeri compresi fra 0 ed 8
matrice = np.arange(9).reshape(3,3)
print(matrice)


#Vettore casuale di 30 elementi con media
vettore = rdm.random((1,30))
media = np.mean(vettore)
print('\n')
print("La media del vettore casuale di 30 elementi è",media)

#Indici degli elemnenti che non sono 0 in un array
array = np.array([3,5,0,4,0,8,0])
indici = np.nonzero(array)
print('\n')
print("Gli indici di tale vettore che non sono 0 sono",indici)

#Indici di un vettore ordinato 
vettore_ordinato = rdm.randint(1000,10000,(1,7))
print('\n')
print("Il vettore ordinato di partenza è",vettore_ordinato)
indici_vettore_ordinato = np.argsort(vettore_ordinato)
print("Gli indici del vettore ordinato sono",indici_vettore_ordinato)


#Array2d
array2d = np.random.rand(2, 50).argpartition(2,axis=1)[:,:2]+1
array2d
media_colonna = np.mean(array2d,axis=0)
media_riga = np.mean(array2d,axis=1)
print('\n')
print("Il vettore casuale di partenza è",array2d)
print("La media di ogni colonna dell'array2d è",media_colonna)
print("La media di ogni riga dell'array2d è",media_riga)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


La media del vettore casuale di 30 elementi è 0.4715072030950511


Gli indici di tale vettore che non sono 0 sono (array([0, 1, 3, 5], dtype=int64),)


Il vettore ordinato di partenza è [[1671 4748 6206 9157 8400 1725 3027]]
Gli indici del vettore ordinato sono [[0 5 6 1 2 4 3]]


Il vettore casuale di partenza è [[11  7]
 [40 14]]
La media di ogni colonna dell'array2d è [25.5 10.5]
La media di ogni riga dell'array2d è [ 9. 27.]


In [9]:
#Trovare indici del vettore ordinato senza libreria numpy
def argsort(vettore_senza_numpy): 
    return sorted(range(len(vettore_senza_numpy)), key=vettore_senza_numpy.__getitem__)
argsort([1023,5202 ,6230 ,1671 ,1682 ,5241 ,4532])

[0, 3, 4, 6, 1, 5, 2]